config/routes.rb
Rails.application.routes.draw do
  # 管理者用
  devise_for :admins, skip: [:registrations, :passwords], controllers: {
    sessions: 'admin/sessions'
  }
  namespace :admin do
    root to: 'homes#top'
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
    resources :items, except: [:destroy]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
  end
  # 会員側
  devise_for :customers, skip: [:passwords], controllers: {
    sessions: 'public/sessions',
    registrations: 'public/registrations'
  }
  scope module: :public do
    root to: 'homes#top'
    get 'about' => "homes#about", as: "about"
    get "customers/my_page" => "customers#show", as: "my_page"
    get 'customers/information/edit' => 'customers#edit', as: 'edit_information'
    patch 'customers/information' => 'customers#update', as: 'update_information'
    get 'customers/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
    patch 'customers/withdraw' => 'customers#withdraw', as: 'withdraw'
    resources :items, only: [:index, :show]
    resources :addresses, except: [:new, :show]
    resources :cart_items, only: [:index, :create, :update, :destroy]
    delete 'cart_items' => 'cart_items#destroy_all', as: 'destroy_all_cart_items'
    post 'orders/confirm' => 'orders#confirm', as: 'confirm'
    get 'orders/thanks' => 'orders#thanks', as: 'thanks'
    resources :orders, only: [:new, :create, :index, :show]
  end
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy

  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true

  def get_item_image(width, height)
    unless image.attached?
      file_path = Rails.root.join("app/assets/images/no_image.jpg")
      image.attach(io: File.open(file_path), filename: "default-image.jpg", content_type: "image/jpeg")
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

  def with_tax_price
    (price * 1.1).floor
  end

  def subtotal(cart_item)
    item.with_tax_price * amount
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  def index
    if params[:search].present?
      @items = Item.where('name LIKE ?', "%#{params[:search]}%").page(params[:page]).per(8)
    else
      @items = Item.page(params[:page]).per(8)
    end
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_items_path
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    item = Item.find(params[:id])
    item.update(item_params)
    redirect_to admin_item_path(item)
  end

  private
  def item_params
    params.require(:item).permit(:image, :name, :introduction, :price, :genre_id, :is_active)
  end
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/edit.html.erb
<h1>商品編集</h1>
<%= form_with model: [:admin, @item], local:true do |f| %>
  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :introduction %>
    <%= f.text_area :introduction %>
  </div>
  <div class="field">
    <%= f.label :genre_id %>
    <%= f.select :genre_id, options_from_collection_for_select(Genre.all, :id, :name, @item.genre_id) %>
  </div>
  <div class="field">
    <%= f.label :price %>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :is_active %>
    <%= f.radio_button :is_active, true %>
    <%= f.label :is_active, '販売中' %>
    <%= f.radio_button :is_active, false %>
    <%= f.label :is_active, '販売停止中' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/items/index.html.erb
<h1>商品一覧</h1>
<%= link_to '新規商品登録', new_admin_item_path %>
<table>
  <tr>
    <th>商品ID</th>
    <th>商品名</th>
    <th>税抜価格</th>
    <th>ジャンル</th>
    <th>ステータス</th>
  </tr>
  <% @items.each do |item| %>
    <tr>
      <td><%= item.id %></td>
      <td><%= link_to item.name, admin_item_path(item) %></td>
      <td><%= item.price %></td>
      <td><%= item.genre.name %></td>
      <td><%= item.is_active ? '販売中' : '販売停止中' %></td>
    </tr>
  <% end %>
</table>
<%= paginate @items %>

app/views/admin/items/new.html.erb
<h1>商品新規登録</h1>
<%= form_with model:[:admin,@item], local:true do |f| %>
  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image, accept: "image/*" %>
  </div>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :introduction %>
    <%= f.text_area :introduction %>
  </div>
  <div class="field">
    <%= f.label :genre_id %>
    <%= f.select :genre_id, options_from_collection_for_select(Genre.all, :id, :name) %>
  </div>
  <div class="field">
    <%= f.label :price %>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :is_active %>
    <%= f.radio_button :is_active, true %>
    <%= f.label :is_active, '販売中' %>
    <%= f.radio_button :is_active, false %>
    <%= f.label :is_active, '販売停止中' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/items/show.html.erb
<h1>商品詳細</h1>
<div>
  <%= image_tag @item.get_item_image(1024, 1024) %>
</div>
<div>
  <%= @item.name %><br>
  <%= @item.introduction %><br>
  <%= @item.genre.name %><br>
  <%= @item.with_tax_price %>（<%= @item.price %>）<br>
  <%= @item.is_active ? '販売中' : '販売停止中' %><br>
  <%= link_to '編集', edit_admin_item_path(@item) %>
</div>