config/routes.rb
Rails.application.routes.draw do
  # 管理者用
  devise_for :admins, skip: [:registrations, :passwords], controllers: {
    sessions: 'admin/sessions'
  }
  namespace :admin do
    root to: 'homes#top'
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
    resources :items, except: [:destroy]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
  end
  # 会員側
  devise_for :customers, skip: [:passwords], controllers: {
    sessions: 'public/sessions',
    registrations: 'public/registrations'
  }
  scope module: :public do
    root to: 'homes#top'
    get 'about' => "homes#about", as: "about"
    get "customers/my_page" => "customers#show", as: "my_page"
    get 'customers/information/edit' => 'customers#edit', as: 'edit_information'
    patch 'customers/information' => 'customers#update', as: 'update_information'
    get 'customers/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
    patch 'customers/withdraw' => 'customers#withdraw', as: 'withdraw'
    resources :items, only: [:index, :show]
    resources :addresses, except: [:new, :show]
    resources :cart_items, only: [:index, :create, :update, :destroy]
    delete 'cart_items' => 'cart_items#destroy_all', as: 'destroy_all_cart_items'
    post 'orders/confirm' => 'orders#confirm', as: 'confirm'
    get 'orders/thanks' => 'orders#thanks', as: 'thanks'
    resources :orders, only: [:new, :create, :index, :show]
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :name, presence: true
  validates :payment_method, presence: true

  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { waiting: 0, confirm: 1, making: 2, preparing: 3, shipped: 4 }
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!
  def show
    @order = Order.find(params[:id])
    @order_detail = @order.order_details
    @total_price = 0
    @order_detail.each do |order_detail|
      @total_price += order_detail.item.with_tax_price * order_detail.amount
    end
  end

  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    if @order.status == "confirm"
      @order.order_details.each do |order_detail|
        order_detail.update(making_status: 1)
      end
    end
    redirect_to admin_order_path(@order)
  end

  private
  def order_params
    params.require(:order).permit(:status)
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/show.html.erb
<h1>注文履歴詳細</h1>
<table>
  <tr>
    <th>購入者</th>
    <td><%= link_to @order.customer.last_name + @order.customer.first_name, admin_customer_path(@order.customer) %></td>
  </tr>
  <tr>
    <th>注文日</th>
    <td><%= @order.created_at.strftime("%Y/%m/%d") %></td>
  </tr>
  <tr>
    <th>配送先</th>
    <td>
      <%= "〒" + @order.postal_code + @order.address %><br>
      <%= @order.name %>
    </td>
  </tr>
  <tr>
    <th>支払方法</th>
    <td><%= @order.payment_method_i18n %></td>
  </tr>
  <tr>
    <th>注文ステータス</th>
    <td>
      <%= form_with model:@order, url:admin_order_path(@order), method: :patch do |f| %>
        <%= f.select :status, options_from_collection_for_select(Order.statuses_i18n, :first, :last, @order.status) %>
        <%= f.submit "更新" %>
      <% end %>
    </td>
  </tr>
</table>
<table>
  <tr>
    <th>商品名</th>
    <th>単価（税込）</th>
    <th>数量</th>
    <th>小計</th>
    <th>製作ステータス</th>
  </tr>
  <% @order.order_details.each do |order_detail| %>
    <tr>
      <td><%= order_detail.item.name %></td>
      <td><%= order_detail.price %></td>
      <td><%= order_detail.amount %></td>
      <td><%= order_detail.subtotal %></td>
      <td>
        <%= form_with model:order_detail, url:admin_order_detail_path(order_detail), method: :patch do |f| %>
          <%= f.select :making_status, options_from_collection_for_select(OrderDetail.making_statuses_i18n, :first, :last, order_detail.making_status) %>
          <%= f.submit "更新" %>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>

<table>
  <tr>
    <th>商品合計</th>
    <td><%= @total_price %>円</td>
  </tr>
  <tr>
    <th>送料</th>
    <td><%= @order.shipping_cost %>円</td>
  </tr>
  <tr>
    <th>請求金額合計</th>
    <td><%= @order.total_payment %>円</td>
  </tr>
</table>