config/routes.rb
Rails.application.routes.draw do
  # 管理者用
  devise_for :admins, skip: [:registrations, :passwords], controllers: {
    sessions: 'admin/sessions'
  }
  namespace :admin do
    root to: 'homes#top'
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
    resources :items, except: [:destroy]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
  end
  # 会員側
  devise_for :customers, skip: [:passwords], controllers: {
    sessions: 'public/sessions',
    registrations: 'public/registrations'
  }
  scope module: :public do
    root to: 'homes#top'
    get 'about' => "homes#about", as: "about"
    get "customers/my_page" => "customers#show", as: "my_page"
    get 'customers/information/edit' => 'customers#edit', as: 'edit_information'
    patch 'customers/information' => 'customers#update', as: 'update_information'
    get 'customers/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
    patch 'customers/withdraw' => 'customers#withdraw', as: 'withdraw'
    resources :items, only: [:index, :show]
    resources :addresses, except: [:new, :show]
    resources :cart_items, only: [:index, :create, :update, :destroy]
    delete 'cart_items' => 'cart_items#destroy_all', as: 'destroy_all_cart_items'
    post 'orders/confirm' => 'orders#confirm', as: 'confirm'
    get 'orders/thanks' => 'orders#thanks', as: 'thanks'
    resources :orders, only: [:new, :create, :index, :show]
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :name, presence: true

  def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item

  def with_tax_price
    (item.price * 1.1).floor
  end

  def subtotal(cart_item)
    item.with_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true

  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
end

app/models/genre.rb
class Genre < ApplicationRecord
  validates :name, presence: true
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy

  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true

  def get_item_image(width, height)
    unless image.attached?
      file_path = Rails.root.join("app/assets/images/no_image.jpg")
      image.attach(io: File.open(file_path), filename: "default-image.jpg", content_type: "image/jpeg")
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

  def with_tax_price
    (price * 1.1).floor
  end

  def subtotal(cart_item)
    item.with_tax_price * amount
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :name, presence: true
  validates :payment_method, presence: true

  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { waiting: 0, confirm: 1, making: 2, preparing: 3, shipped: 4 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
  enum making_status: { not_start: 0, waiting: 1, in_progress: 2, done: 3 }

  def subtotal
    item.with_tax_price * amount
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!
  def index
    @genre = Genre.new
    @genres = Genre.page(params[:page]).per(8)
  end

  def create
    genre = Genre.new(genre_params)
    genre.save
    redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    genre = Genre.find(params[:id])
    genre.update(genre_params)
    redirect_to admin_genres_path
  end

  private
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  def top
    @orders = Order.page(params[:page]).per(10)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  def index
    if params[:search].present?
      @items = Item.where('name LIKE ?', "%#{params[:search]}%").page(params[:page]).per(8)
    else
      @items = Item.page(params[:page]).per(8)
    end
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_items_path
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    item = Item.find(params[:id])
    item.update(item_params)
    redirect_to admin_item_path(item)
  end

  private
  def item_params
    params.require(:item).permit(:image, :name, :introduction, :price, :genre_id, :is_active)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-md navbar-light bg-light px-3">
  <%= link_to "NaganoCake", root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <div class="ml-auto">
      <div>
        <ul class="navbar-nav">
          <% if customer_signed_in? %> <!-- 会員がログインしている場合 -->
            <li class="nav-item my-2">
              <%= link_to "マイページ", my_page_path, class: "nav-link btn btn-outline-secondary px-3 py-2" %>
            </li>
            <li class="nav-item my-2">
              <%= link_to "商品一覧", items_path, class: "nav-link btn btn-outline-secondary px-3 py-2 ml-md-3" %>
            </li>
            <li class="nav-item my-2">
              <%= link_to "カート", cart_items_path, class: "nav-link btn btn-outline-secondary px-3 py-2 ml-md-3" %>
            </li>
            <li class="nav-item my-2">
              <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, data: { confirm: "本当にログアウトしますか？" }, class: "nav-link btn btn-outline-secondary px-3 py-2 ml-md-3" %>
            </li>
          <% elsif admin_signed_in? %> <!-- 管理者がログインしている場合 -->
            <li class="nav-item my-2">
              <%= link_to "商品一覧", admin_items_path, class: "nav-link btn btn-outline-secondary px-3 py-2" %>
            </li>
            <li class="nav-item my-2">
              <%= link_to "会員一覧", admin_customers_path, class: "nav-link btn btn-outline-secondary px-3 py-2 ml-md-3" %>
            </li>
            <li class="nav-item my-2">
              <%= link_to "注文履歴一覧", admin_root_path, class: "nav-link btn btn-outline-secondary px-3 py-2 ml-md-3" %>
            </li>
            <li class="nav-item my-2">
              <%= link_to "ジャンル一覧", admin_genres_path, class: "nav-link btn btn-outline-secondary px-3 py-2 ml-md-3" %>
            </li>
            <li class="nav-item my-2">
              <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, data: { confirm: "本当にログアウトしますか？" }, class: "nav-link btn btn-outline-secondary px-3 py-2 ml-md-3" %>
            </li>
          <% else %> <!-- 誰もログインしていない場合 -->
            <li class="nav-item my-2">
              <%= link_to "about", about_path, class: "nav-link btn btn-outline-secondary px-3 py-2" %>
            </li>
            <li class="nav-item my-2">
              <%= link_to "商品一覧", items_path, class: "nav-link btn btn-outline-secondary px-3 py-2 ml-md-3" %>
            </li>
            <li class="nav-item my-2">
              <%= link_to "新規登録", new_customer_registration_path, class: "nav-link btn btn-outline-secondary px-3 py-2 ml-md-3" %>
            </li>
            <li class="nav-item my-2">
              <%= link_to "ログイン", new_customer_session_path, class: "nav-link btn btn-outline-secondary px-3 py-2 ml-md-3" %>
            </li>
          <% end %>
        </ul>
      </div>
      <div>
        <% if customer_signed_in? %> <!-- 会員がログインしている場合 -->
          <%= form_with url: items_path, method: :get, class:"form-inline my-2 my-lg-0 mr-3 justify-content-end" do |f| %>
            <%= f.text_field :search, class: "form-control mr-sm-2", placeholder: "Search", aria_label: "Search" %>
            <%= f.submit "Search", class: "btn btn-outline-success my-2 my-sm-0" %>
          <% end %>
        <% elsif admin_signed_in? %> <!-- 管理者がログインしている場合 -->
          <%= form_with url: admin_items_path, method: :get, class:"form-inline my-2 my-lg-0 mr-3 justify-content-end" do |f| %>
            <%= f.text_field :search, class: "form-control mr-sm-2", placeholder: "Search", aria_label: "Search" %>
            <%= f.submit "Search", class: "btn btn-outline-success my-2 my-sm-0" %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header><%= render 'layouts/header' %></header>
    <main class="container my-4"><%= yield %></main>
  </body>
</html>